trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

steps:
    -   task: GoTool@0
        displayName: "Install GO"
        inputs:
            version: '1.14.1'
    -   task: Go@0
        displayName: "get dependencies"
        inputs:
            command: 'get'
            arguments: '-d'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
    -   task: Go@0
        displayName: "build"
        inputs:
            command: 'build'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
    -   task: CopyFiles@2
        displayName: "artifacts"
        inputs:
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
    -   task: Go@0
        displayName: "test"
        inputs:
            command: 'test'
            arguments: '-v'
            workingDirectory: '$(modulePath)'
    -   task: PublishBuildArtifacts@1
        inputs:
            artifactName: drop
