trigger:
    - master
pool:
    vmImage: 'Ubuntu 16.04'

variables:
    imageName: 'pipelines-go:$(build.buildId)'

steps:
    - script: docker build -f Dockerfile -t $(imageName) .
      displayName: 'docker build'