# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
    branches:
        include:
            - master
    paths:
        exclude:
            - README.md
            - .gitignore

pr:
    autoCancel: false
    branches:
        include:
            - master
    paths:
        exclude:
            - README.md
            - .gitignore

variables:
    GOPATH: '$(Pipeline.Workspace)/gowork'

stages:
    -   stage: Build
        jobs:
            -   template: templates/azure/jobs/build.yml   # Linux Build
                parameters:
                    name: 'Linux_Build'
                    pool:
                        vmImage: 'ubuntu-18.04'

    -   stage: Test
        dependsOn:
            - Build
        jobs:
            -   template: templates/azure/jobs/test.yml
                parameters:
                      name: 'Tests'

    -   stage: Deploy
        dependsOn:
            - Build
            - Test
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        jobs:
            -   template: templates/azure/jobs/deploy.yml
                parameters:
                    name: 'gcloud'
