trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: GoTool@0
      inputs:
          version: '1.14.1'
    - task: Go@0
      inputs:
          command: 'get'
          arguments: '-d'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: Go@0
      inputs:
          command: 'build'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: CopyFiles@2
      inputs:
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
          artifactName: drop