version: '3.7'

services:
    gcloud:
        image: 'gcr.io/cloud-builders/gcloud-slim:latest'
        volumes:
            -   type: bind
                source: .
                target: /pipeline
        entrypoint: /pipeline/templates/azure/scripts/entrypoint.sh
        command: /pipeline/templates/azure/scripts/do.sh
        environment:
            - PROJECT=smiling-breaker-269508