// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Dictionary
//
//  Just a dictionary for "Галицька" language.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
