// Code generated by go-swagger; DO NOT EDIT.

package words

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddWordHandlerFunc turns a function with the right signature into a add word handler
type AddWordHandlerFunc func(AddWordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddWordHandlerFunc) Handle(params AddWordParams) middleware.Responder {
	return fn(params)
}

// AddWordHandler interface for that can handle valid add word params
type AddWordHandler interface {
	Handle(AddWordParams) middleware.Responder
}

// NewAddWord creates a new http.Handler for the add word operation
func NewAddWord(ctx *middleware.Context, handler AddWordHandler) *AddWord {
	return &AddWord{Context: ctx, Handler: handler}
}

/* AddWord swagger:route POST /words words addWord

Add a new word to the dictionary

*/
type AddWord struct {
	Context *middleware.Context
	Handler AddWordHandler
}

func (o *AddWord) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddWordParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// AddWordOKBody add word o k body
//
// swagger:model AddWordOKBody
type AddWordOKBody struct {

	// id
	// Required: true
	ID *uint64 `json:"id"`
}

// Validate validates this add word o k body
func (o *AddWordOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddWordOKBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("addWordOK"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this add word o k body based on context it is used
func (o *AddWordOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AddWordOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddWordOKBody) UnmarshalBinary(b []byte) error {
	var res AddWordOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
