// Code generated by go-swagger; DO NOT EDIT.

package words

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteWordHandlerFunc turns a function with the right signature into a delete word handler
type DeleteWordHandlerFunc func(DeleteWordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteWordHandlerFunc) Handle(params DeleteWordParams) middleware.Responder {
	return fn(params)
}

// DeleteWordHandler interface for that can handle valid delete word params
type DeleteWordHandler interface {
	Handle(DeleteWordParams) middleware.Responder
}

// NewDeleteWord creates a new http.Handler for the delete word operation
func NewDeleteWord(ctx *middleware.Context, handler DeleteWordHandler) *DeleteWord {
	return &DeleteWord{Context: ctx, Handler: handler}
}

/*DeleteWord swagger:route DELETE /words/{wordId} words deleteWord

Delete a word

*/
type DeleteWord struct {
	Context *middleware.Context
	Handler DeleteWordHandler
}

func (o *DeleteWord) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteWordParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteWordOKBody delete word o k body
//
// swagger:model DeleteWordOKBody
type DeleteWordOKBody struct {

	// id
	// Required: true
	ID *uint64 `json:"id"`
}

// Validate validates this delete word o k body
func (o *DeleteWordOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteWordOKBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("deleteWordOK"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteWordOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteWordOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteWordOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
