// Code generated by go-swagger; DO NOT EDIT.

package words

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"dictionary/api/models"
)

// GetWordOKCode is the HTTP code returned for type GetWordOK
const GetWordOKCode int = 200

/*GetWordOK successful operation

swagger:response getWordOK
*/
type GetWordOK struct {

	/*
	  In: Body
	*/
	Payload *models.Word `json:"body,omitempty"`
}

// NewGetWordOK creates GetWordOK with default headers values
func NewGetWordOK() *GetWordOK {

	return &GetWordOK{}
}

// WithPayload adds the payload to the get word o k response
func (o *GetWordOK) WithPayload(payload *models.Word) *GetWordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get word o k response
func (o *GetWordOK) SetPayload(payload *models.Word) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetWordBadRequestCode is the HTTP code returned for type GetWordBadRequest
const GetWordBadRequestCode int = 400

/*GetWordBadRequest Invalid Word ID

swagger:response getWordBadRequest
*/
type GetWordBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorBadRequest `json:"body,omitempty"`
}

// NewGetWordBadRequest creates GetWordBadRequest with default headers values
func NewGetWordBadRequest() *GetWordBadRequest {

	return &GetWordBadRequest{}
}

// WithPayload adds the payload to the get word bad request response
func (o *GetWordBadRequest) WithPayload(payload *models.ErrorBadRequest) *GetWordBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get word bad request response
func (o *GetWordBadRequest) SetPayload(payload *models.ErrorBadRequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetWordNotFoundCode is the HTTP code returned for type GetWordNotFound
const GetWordNotFoundCode int = 404

/*GetWordNotFound Word not found

swagger:response getWordNotFound
*/
type GetWordNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorNotFound `json:"body,omitempty"`
}

// NewGetWordNotFound creates GetWordNotFound with default headers values
func NewGetWordNotFound() *GetWordNotFound {

	return &GetWordNotFound{}
}

// WithPayload adds the payload to the get word not found response
func (o *GetWordNotFound) WithPayload(payload *models.ErrorNotFound) *GetWordNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get word not found response
func (o *GetWordNotFound) SetPayload(payload *models.ErrorNotFound) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetWordInternalServerErrorCode is the HTTP code returned for type GetWordInternalServerError
const GetWordInternalServerErrorCode int = 500

/*GetWordInternalServerError Internal Server Error

swagger:response getWordInternalServerError
*/
type GetWordInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorInternalError `json:"body,omitempty"`
}

// NewGetWordInternalServerError creates GetWordInternalServerError with default headers values
func NewGetWordInternalServerError() *GetWordInternalServerError {

	return &GetWordInternalServerError{}
}

// WithPayload adds the payload to the get word internal server error response
func (o *GetWordInternalServerError) WithPayload(payload *models.ErrorInternalError) *GetWordInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get word internal server error response
func (o *GetWordInternalServerError) SetPayload(payload *models.ErrorInternalError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
