// Code generated by go-swagger; DO NOT EDIT.

package words

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetWordsHandlerFunc turns a function with the right signature into a get words handler
type GetWordsHandlerFunc func(GetWordsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWordsHandlerFunc) Handle(params GetWordsParams) middleware.Responder {
	return fn(params)
}

// GetWordsHandler interface for that can handle valid get words params
type GetWordsHandler interface {
	Handle(GetWordsParams) middleware.Responder
}

// NewGetWords creates a new http.Handler for the get words operation
func NewGetWords(ctx *middleware.Context, handler GetWordsHandler) *GetWords {
	return &GetWords{Context: ctx, Handler: handler}
}

/* GetWords swagger:route GET /words words getWords

Get all words

*/
type GetWords struct {
	Context *middleware.Context
	Handler GetWordsHandler
}

func (o *GetWords) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetWordsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
