swagger: "2.0"
info:
  description: "Just a dictionary for \"Галицька\" language."
  version: "1.0.0"
  title: "Dictionary"
externalDocs:
  description: "GitHub"
  url: "https://github.com/yushni/dictionary"
host: "localhost"
basePath: "/"
tags:
  - name: "words"
schemes:
  - "http"
paths:
  /words:
    post:
      tags:
        - "words"
      summary: "Add a new word to the dictionary"
      operationId: "addWord"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Metadata of the word that have to be added to the dictionary"
          required: true
          schema:
            $ref: "#/definitions/Word"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "object"
            required:
              - "id"
            properties:
              id:
                type: "integer"
                format: "uint64"
        "400":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ErrorBadRequest"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalError"
    get:
      tags:
        - "words"
      summary: "Get all words"
      produces:
        - "application/json"
      parameters:
        - name: "limit"
          in: "query"
          required: false
          type: "integer"
          format: "uint64"
          default: 20
        - name: "offset"
          in: "query"
          required: false
          type: "integer"
          format: "uint64"
          default: 1
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Word"
        "400":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ErrorBadRequest"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalError"

  /words/{wordId}:
    get:
      tags:
        - "words"
      summary: "Get word by ID"
      operationId: "getWord"
      produces:
        - "application/json"
      parameters:
        - name: "wordId"
          in: "path"
          required: true
          type: "integer"
          format: "uint64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Word"
        "400":
          description: "Invalid Word ID"
          schema:
            $ref: "#/definitions/ErrorBadRequest"
        "404":
          description: "Word not found"
          schema:
            $ref: "#/definitions/ErrorNotFound"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalError"

    delete:
      tags:
        - "words"
      summary: "Delete a word"
      operationId: "deleteWord"
      parameters:
        - name: "wordId"
          in: "path"
          required: true
          type: "integer"
          format: "uint64"
      responses:
        "200":
          description: "Successful deletion"
          schema:
            type: "object"
            required:
              - "id"
            properties:
              id:
                type: "integer"
                format: "uint64"
        "400":
          description: "Invalid Word ID"
          schema:
            $ref: "#/definitions/ErrorBadRequest"
        "404":
          description: "Word not found"
          schema:
            $ref: "#/definitions/ErrorNotFound"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalError"

definitions:
  Translation:
    type: "object"
    required:
      - "translation"
      - "transcription"
    properties:
      translation:
        type: "string"
      transcription:
        type: "string"
  Word:
    type: "object"
    required:
      - "word"
      - "transcription"
      - "translations"
      - "origin"
      - "samples"
    properties:
      id:
        type: "integer"
        format: "uint64"
        readOnly: true
      word:
        type: "string"
      transcription:
        type: "string"
      translations:
        type: "array"
        items:
          $ref: "#/definitions/Translation"
      origin:
        type: "string"
      samples:
        type: "array"
        items:
          type: "string"
  ErrorBadRequest:
    type: "object"
    required:
      - "message"
    properties:
      message:
        type: "string"
  ErrorNotFound:
    type: "object"
    required:
      - "message"
    properties:
      message:
        type: "string"
  ErrorInternalError:
    type: "object"
    required:
      - "message"
    properties:
      message:
        type: "string"